version: '3'
services:
  web: 
    container_name: blog-app
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    links:
      - db:db 
  db:
    container_name: blog-db
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
        - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
        - "3306:3306" 
  phpmyadmin:
      container_name: blog-phpmyadmin
      image: phpmyadmin/phpmyadmin
      depends_on:
        - db
      ports:
          - "8080:80"